import { PHOTOS } from "./photos";

export const META = {
  environment: "staging",
  /** @dev limit is 60 characters only */
  title: "Carlo Miguel Dy — Software Engineer",
  /** @dev limit is 105 characters only */
  description:
    "A full stack software engineer, practices software architecture & test driven development, knows the importance of writing tests, and aims to build a better software by leveraging on software design principles. While he also loves to explore, build and contribute to open-source communities he finds it interesting.",
  /** @todo to be changed into https://carlomigueldy.dev for Production */
  url: "https://staging.carlomigueldy.dev",
  /** @todo to add image url */
  locale: "en_US",
  author: "Carlo Miguel Dy",
  imageUrl: PHOTOS.me,
  imageAlt: "Carlo Miguel's photo",
  keywords: [
    "full stack software engineer",
    "Full Stack Software Engineer",
    "software engineer",
    "Software Engineer",
    "freelance software engineer",
    "Freelance Software Engineer",
    "full stack developer",
    "Full Stack Developer",
    "full stack software developer",
    "Full Stack Software Developer",
    "software developer",
    "Software Developer",
    "freelance software developer",
    "Freelance Software Developer",
    "IT consultant",
    "it consultant",
    "Software Architect",
    "software architect",
    "SQL Developer",
    "sql developer",
    "NoSQL Developer",
    "nosql developer",
    "PostgreSQL Developer",
    "postgresql developer",
    "Postgres Developer",
    "postgres developer",
    "MySQL Developer",
    "mysql developer",
    "Database Engineer",
    "database engineer",
    "Database Designer",
    "database designer",
    "Systems Architect",
    "systems architect",
    "Firestore Security Rules Developer",
    "firestore security rules developer",
    "Firebase Developer",
    "firebase developer",
    "Vuejs Developer",
    "vuejs developer",
    "Vue.js Developer",
    "vue.js developer",
    "Vue Developer",
    "vue developer",
    "Reactjs Developer",
    "reactjs developer",
    "React.js Developer",
    "react.js developer",
    "Angular Developer",
    "angular developer",
    "10X Developer",
    "Unicorn Developer",
    "unicorn developer",
    "Laravel Developer",
    "laravel developer",
    "JavaScript Developer",
    "javascript developer",
    "TypeScript Developer",
    "typescript developer",
    "js developer",
    "ts developer",
    "PHP Developer",
    "php developer",
    "Dart Developer",
    "dart developer",
    "Flutter Developer",
    "flutter developer",
    "Blockchain Developer",
    "blockchain developer",
    "Blockchain Engineer",
    "blockchain engineer",
    "Solidity Developer",
    "solidity developer",
    "Solidity Engineer",
    "solidity engineer",
    "Smart Contract Developer",
    "smart contract developer",
    "Smart Contract Engineer",
    "smart contract engineer",
    "Lead Software Engineer",
    "lead software engineer",
    "Lead Software Developer",
    "lead software developer",
    "carlomigueldy portfolio",
    "CarloMiguelDy portfolio",
    "Carlo Miguel Dy Portfolio",
    "carlo miguel dy portfolio",
    "carlo miguel dy website",
    "Carlo Miguel Dy website",
    "Web 3.0 Engineer",
    "web 3.0 engineer",
    "Web 3.0 Software Engineer",
    "web 3.0 software engineer",
    "Web 3.0 Developer",
    "web 3.0 developer",
    "Web 3.0 Software Developer",
    "web 3.0 software developer",
    "web 3 engineer",
    "web 3 software engineer",
    "web 3 software developer",
    "Ethereum Developer",
    "Ethereum Software Engineer",
    "Ethereum Software Developer",
    "ethereum developer",
    "ethereum software engineer",
    "ethereum software developer",
    "ethereum dev",
    "dyveloper",
    "full stack dyveloper",
    "Full Stack Dyveloper",
    "Dyveloper",
    "serverless developer",
    "Serverless Developer",
    "Serverless Software Engineer",
    "serverless software engineer",
    "Serverless Software Developer",
    "serverless software developer",
    "Supabase Developer",
    "Supabase Engineer",
    "Supabase Full Stack Engineer",
    "Supabase Full Stack Software Engiener",
    "Supabase Full Stack Developer",
  ],
};
